<a href="https://colab.research.google.com/github/mirzakazem/8Puzzle_A-Star-Algorithm/blob/main/8_Puzzle_using_A_Star_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook I will implement the informed version of A* to solve the 8 puzzle Game. 


---


A star is an optimal Algorithm always selects the state with the minimum f.

f= propagation cost (g)+ heuristic(H)

I will use 2 different heuristic measures, Tiles and Manhattan distance.

*in the next cell i will implement the Class state, then in the next two ones I will implement A star with tiles heuristic and Manhattan distance respectively*


In [1]:
import numpy as np
class State:
    def __init__(self,s, zero, prev=None, g=0):
        self.s=s
        self.prev=prev
        self.zero=zero
        self.hash=None
        
        self.g=g
        
        self.tiles_heuristic=self.h_heuristic()
        self.manhattan_heuristic=self.m_heuristic()

        
        self.f_tiles=self.g+self.tiles_heuristic
        self.f_manhattan=self.g+self.manhattan_heuristic
        self.f_kazem=self.g+self.manhattan_heuristic+self.tiles_heuristic
        
        
    def __hash__(self):
        if self.hash:
            return self.hash
        s=0
        for i in range(8,-1,-1):
            s=10*s+self.s[i]
        self.hash=s
        return s
        
    #1,5,6
    #2,0,3
    #4,7,8
    
    #[1,5,6,2,0,3,4,7,8] zero=4
    def Successors(self):
        succ=[]
        s=self.s
        zero=self.zero
        if (zero-1)>=0 and ((zero-1)//3==zero//3):
            tmp=s.copy()
            tmp[zero-1],tmp[zero]=s[zero],s[zero-1]
            succ.append(State(tmp,zero-1,self,self.g+1))
        if (zero+1<9) and ((zero+1)//3==zero//3):
            tmp=s.copy()
            tmp[zero+1],tmp[zero]=s[zero],s[zero+1]
            succ.append(State(tmp,zero+1,self,self.g+1))
        if (zero-3)>=0:
            tmp=s.copy()
            tmp[zero-3],tmp[zero]=s[zero],s[zero-3]
            succ.append(State(tmp,zero-3,self,self.g+1))
        if (zero+3)<=8:
            tmp=s.copy()
            tmp[zero+3],tmp[zero]=s[zero],s[zero+3]
            succ.append(State(tmp,zero+3,self,self.g+1))
        
        return succ
    
    def IsGoal(self):
        solution=[1,2,3,4,5,6,7,8,0]
        s=self.s
        for i in range(9):
            if s[i]!=solution[i]:
                return False
        return True
    
    def __eq__(self, other):
        for i in range(9):
            if self.s[i]!=other.s[i]:
                return False
        return True
    
    def h_heuristic(self):
        goal=[1,2,3,4,5,6,7,8,0]
        h=0
        for i in range(9):
            if self.s[i]!=goal[i]:
                h=h+1
        return h
    
    def m_heuristic(self):
        goal=[1,2,3,4,5,6,7,8,0]
        m=0
        for i in range(len(self.s)):
            stateIndex= self.s.index(self.s[i])
            stateX=stateIndex//3
            stateY=stateIndex%3

            goalIndex = goal.index(self.s[i])
            goalX=goalIndex//3
            goalY=goalIndex%3

            xDif= abs(stateX-goalX)
            yDif= abs(stateY-goalY)

            m=m+(xDif+yDif)
        
        return m
    
    
    def __str__(self):
        
        tmp=np.array(self.s)
        return str(tmp.reshape(3,3))



In [8]:
#this function will return the path from the goal to the root
def Solution(state):
    path=[]
    length=0
    while state:
        path.append(str(state))
        state=state.prev
        length=length+1
    return ('\n'.join(path), length)

# i will use this function to sort the queue based on the f of the state, after appending it
def sorKey(A):
    return A[1]

#state object takes two arguments, state' list and the zero position

start=State([2,8,0,6,3,5,4,7,1],2)

#to add visited state after visiting them
visited=set()

#flag
solved=False
from collections import deque

#the queue
q=[]
q.append([[start],[0]])

#to count the explored states
i=0


while len(q) > 0:
    i=i+1
    current=q.pop()
    current = current[0]
    current = current[0]
    if current.IsGoal():
        path, length= Solution(current)
        print(path)
        print("Moves: "+str(length))
        solved=True
        break
    if current in visited:
        continue
    visited.add(current)
    for tmp in current.Successors():
        #q.append(tmp)
        q.append([[tmp],[tmp.f_tiles]])
        q.sort(reverse=True,key = sorKey) 




if not solved: 
    print("No Solution")
    
print("A* Algorithm with Tiles Heuristic")
print("Total Backward Cost: "+str(current.g))
print("Visited states: "+str(len(visited)))
print("Explored: "+str(i))

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [0 5 6]
 [4 7 8]]
[[0 2 3]
 [1 5 6]
 [4 7 8]]
[[2 0 3]
 [1 5 6]
 [4 7 8]]
[[2 5 3]
 [1 0 6]
 [4 7 8]]
[[2 5 3]
 [0 1 6]
 [4 7 8]]
[[2 5 3]
 [4 1 6]
 [0 7 8]]
[[2 5 3]
 [4 1 6]
 [7 0 8]]
[[2 5 3]
 [4 0 6]
 [7 1 8]]
[[2 5 3]
 [4 6 0]
 [7 1 8]]
[[2 5 3]
 [4 6 8]
 [7 1 0]]
[[2 5 3]
 [4 6 8]
 [7 0 1]]
[[2 5 3]
 [4 6 8]
 [0 7 1]]
[[2 5 3]
 [0 6 8]
 [4 7 1]]
[[2 5 3]
 [6 0 8]
 [4 7 1]]
[[2 5 3]
 [6 8 0]
 [4 7 1]]
[[2 5 0]
 [6 8 3]
 [4 7 1]]
[[2 0 5]
 [6 8 3]
 [4 7 1]]
[[2 8 5]
 [6 0 3]
 [4 7 1]]
[[2 8 5]
 [6 3 0]
 [4 7 1]]
[[2 8 0]
 [6 3 5]
 [4 7 1]]
Moves: 23
A* Algorithm with Tiles Heuristic
Total Backward Cost: 22
Visited states: 5783
Explored: 9505


In [10]:
#this function will return the path from the goal to the root
def Solution(state):
    path=[]
    length=0
    while state:
        path.append(str(state))
        state=state.prev
        length=length+1
    return ('\n'.join(path), length)

# i will use this function to sort the queue based on the f of the state, after appending it
def sorKey(A):
    return A[1]

#state object takes two arguments, state' list and the zero position
start=State([2,8,0,6,3,5,4,7,1],2)

#to add visited state after visiting them
visited=set()

#flag
solved=False
from collections import deque

#the queue
q=[]
q.append([[start],[0]])

#to count the explored states
i=0


while len(q) > 0:
    i=i+1
    current=q.pop()
    current = current[0]
    current = current[0]
    if current.IsGoal():
        path, length= Solution(current)
        print(path)
        print("Moves: "+str(length))
        solved=True
        break
    if current in visited:
        continue
    visited.add(current)
    for tmp in current.Successors():
        #q.append(tmp)
        q.append([[tmp],[tmp.f_manhattan]])
        q.sort(reverse=True,key = sorKey) 


if not solved: 
    print("No Solution")
    
print("A* Algorithm with Manhatten Heuristic")
print("Total Backward Cost: "+str(current.g))
print("Visited states: "+str(len(visited)))
print("Explored: "+str(i))

[[1 2 3]
 [4 5 6]
 [7 8 0]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [0 5 6]
 [4 7 8]]
[[0 2 3]
 [1 5 6]
 [4 7 8]]
[[2 0 3]
 [1 5 6]
 [4 7 8]]
[[2 5 3]
 [1 0 6]
 [4 7 8]]
[[2 5 3]
 [0 1 6]
 [4 7 8]]
[[2 5 3]
 [4 1 6]
 [0 7 8]]
[[2 5 3]
 [4 1 6]
 [7 0 8]]
[[2 5 3]
 [4 1 6]
 [7 8 0]]
[[2 5 3]
 [4 1 0]
 [7 8 6]]
[[2 5 3]
 [4 0 1]
 [7 8 6]]
[[2 5 3]
 [4 8 1]
 [7 0 6]]
[[2 5 3]
 [4 8 1]
 [7 6 0]]
[[2 5 3]
 [4 8 0]
 [7 6 1]]
[[2 5 0]
 [4 8 3]
 [7 6 1]]
[[2 0 5]
 [4 8 3]
 [7 6 1]]
[[2 8 5]
 [4 0 3]
 [7 6 1]]
[[2 8 5]
 [4 6 3]
 [7 0 1]]
[[2 8 5]
 [4 6 3]
 [0 7 1]]
[[2 8 5]
 [0 6 3]
 [4 7 1]]
[[2 8 5]
 [6 0 3]
 [4 7 1]]
[[2 8 5]
 [6 3 0]
 [4 7 1]]
[[2 8 0]
 [6 3 5]
 [4 7 1]]
Moves: 25
A* Algorithm with Manhatten Heuristic
Total Backward Cost: 24
Visited states: 2157
Explored: 3808
